version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: "@angular/language-service"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
    - 3.6.4
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: "@ngneat/transloco"
    versions:
    - 2.20.0
  - dependency-name: karma-jasmine
    versions:
    - 4.0.1
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
